language: crystal
dist: xenial
crystal:
  - latest
  - nightly
addons:
  chrome: stable
services:
  - postgresql
before_install:
  # Setup chromedriver for LuckyFlow
  - sudo apt-get install chromium-chromedriver
matrix:
  allow_failures:
    - crystal: nightly
script:
  # Install Lucky CLI
  - crystal build src/lucky.cr --no-debug --release
  - sudo cp lucky /usr/local/bin
  # Run specs
  - crystal spec -D run-deploy-specs
  # Build docs
  - crystal docs src/lucky_cli.cr
notifications:
  email: false
deploy:
  provider: pages
  skip_cleanup: true
  token: $GITHUB_TOKEN
  project_name: lucky_cli
  on:
    branch: master
  local_dir: docs
